#!/bin/sh
#The Line endings must be LF. Otherwise sh won't interpret this script (this holds true both for Linux _and_ Windows). Please take care when editing this script on a Windows machine, that you don't accidentally change the line endings to CRLF...

test "" = "$(grep -E '#[[:digit:]]{6}' "$1")" && {
   echo "Every commit message must include a Hiszilla ticket No." >&2 
   echo "Expected format: #123456" >&2 
   exit 1
}

#If grep finds something it returns exit code 0.
grep -Eq '#[[:digit:]]{6}[[:alnum:]_]' $1
test $? -eq 0 && {
   echo "Hiszilla ticket No. must not be followed by an alphanumeric character or an underscore [0-9A-Za-z_]" >&2 
   exit 1
}

exit 0